### ISSUE TITLE
SQLI Injection broken!

### ISSUE THREAD

**Issue by Sicarios** [krintoxi/NoobSecToolkit#2]
SQL Injection with SQLMAP seems to be broken with a lib error:
Traceback (most recent call last):
  File "tools/sqli/sqlmap.py", line 22, in <module>
    from lib.utils import versioncheck  # this has to be the first non-standard import
ImportError: No module named lib.utils

**Comment by krintoxi** [comment]
This issue has now been fixed :+1:  :)
